author: Google Summer of Code
github: https://github.com/sahitpj
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/sahitpj"
    - icon: fa-linkedin
      link: "https://linkedin.com/sahitpj"
    - icon: fa-github
      link: "https://github.com/sahitpj"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: XML Feed
      url: /feed.xml

url: "https://sahitpj.github.io/gs"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
